### ISSUE TITLE
Game crashes and exits to main menu (BUG)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#146] opened 2020-01-03 21:39 UTC
1. Description of bug 
• Context – When entering the third room of the tutorial level, the game crashes and the main menu appears.
• Expected output – Not to crash
• Actual output – Crashed
 
2. Minimal steps to reproduce
 • Enter the tutorial
• Progress to the third room, and wait for less than 10 seconds.
 
3. Appearance of bug
Isolated to the third room in the tutorial level.

4. System configuration
Graphics Startup Settings: 1920x1080, Very low quality, full-screen mode.
OS: Windows 10
Specs: 64-bit, Intel CPU, 32GB RAM
Controller: PS3 controller, driver: SCP-DS-Driver-Package

**Comment by trudeaua** [comment] 2020-01-15 18:00
Duplicate of #140

**Closed by trudeaua** 2020-01-15 18:00 UTC
Labels: duplicate
