### ISSUE TITLE
Pick-up animation plays even when player cannot pick up object (BUG)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#166] opened 2020-01-07 01:59 UTC
Description of bug
Context: I attempted to pick up a yellow block as a green player

Expected Output: Nothing, or sound indicating that player cannot pick up that item

Actual Output: Player did not pick it up but animation still played

Minimal steps to reproduce
i) Go to Level 1
ii) Reach the first puzzle
iii) Attempt to pick up a rock that is a different colour from the player

Appearances:
This happened every single time I tried to recreate it. 

Potential Fix(es):
-Make sure the animation state only changes if the player is actually carrying something

System configuration
Resolution: 1920x1080, Full Screen
OS: Windows 10.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, NVIDIA GEFORCE, 64 bit, 12 GB RAM

**Comment by trudeaua** [comment] 2020-01-15 18:07
Duplicate of #149

**Closed** 2020-01-15 19:05 UTC
Labels: bug, duplicate
